package spring.adog.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ID
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.NAME
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    private String NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ACCOUNT_ID
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    private String ACCOUNT_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.TOKEN
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    private String TOKEN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.GMT_CREATE
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    private Long GMT_CREATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.GMT_MODIFIED
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    private Long GMT_MODIFIED;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.BIO
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    private String BIO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.AVATAR_URL
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    private String AVATAR_URL;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.ID
     *
     * @return the value of USER.ID
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.ID
     *
     * @param ID the value for USER.ID
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.NAME
     *
     * @return the value of USER.NAME
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.NAME
     *
     * @param NAME the value for USER.NAME
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.ACCOUNT_ID
     *
     * @return the value of USER.ACCOUNT_ID
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public String getACCOUNT_ID() {
        return ACCOUNT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.ACCOUNT_ID
     *
     * @param ACCOUNT_ID the value for USER.ACCOUNT_ID
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public void setACCOUNT_ID(String ACCOUNT_ID) {
        this.ACCOUNT_ID = ACCOUNT_ID == null ? null : ACCOUNT_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.TOKEN
     *
     * @return the value of USER.TOKEN
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public String getTOKEN() {
        return TOKEN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.TOKEN
     *
     * @param TOKEN the value for USER.TOKEN
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public void setTOKEN(String TOKEN) {
        this.TOKEN = TOKEN == null ? null : TOKEN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.GMT_CREATE
     *
     * @return the value of USER.GMT_CREATE
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public Long getGMT_CREATE() {
        return GMT_CREATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.GMT_CREATE
     *
     * @param GMT_CREATE the value for USER.GMT_CREATE
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public void setGMT_CREATE(Long GMT_CREATE) {
        this.GMT_CREATE = GMT_CREATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.GMT_MODIFIED
     *
     * @return the value of USER.GMT_MODIFIED
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public Long getGMT_MODIFIED() {
        return GMT_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.GMT_MODIFIED
     *
     * @param GMT_MODIFIED the value for USER.GMT_MODIFIED
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public void setGMT_MODIFIED(Long GMT_MODIFIED) {
        this.GMT_MODIFIED = GMT_MODIFIED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.BIO
     *
     * @return the value of USER.BIO
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public String getBIO() {
        return BIO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.BIO
     *
     * @param BIO the value for USER.BIO
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public void setBIO(String BIO) {
        this.BIO = BIO == null ? null : BIO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.AVATAR_URL
     *
     * @return the value of USER.AVATAR_URL
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public String getAVATAR_URL() {
        return AVATAR_URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.AVATAR_URL
     *
     * @param AVATAR_URL the value for USER.AVATAR_URL
     *
     * @mbg.generated Wed Jul 10 19:22:24 CST 2019
     */
    public void setAVATAR_URL(String AVATAR_URL) {
        this.AVATAR_URL = AVATAR_URL == null ? null : AVATAR_URL.trim();
    }
}